# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
- job: Build
  displayName: "Build, Test and Publish"

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: './src/StaticWebAssets.sln -c Release -o packages'
    displayName: 'Create NuGet Packages'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: './test/StaticAssetsTest.sln'
      testRunTitle: 'Run unit tests'
    displayName: 'Test for Assets Discovery'

  - script: dotnet publish ./test/Website/Website.csproj -c Release -o publish
    displayName: 'Test Project Publishing'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'nuget'
      arguments: 'push --skip-duplicate -s https://nuget.xylab.fun/v3/index.json -k $(NUGET_KEY) "packages/**/*.nupkg"'
    displayName: 'Push to NuGet Feed'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
